# Generated by Django 4.1.2 on 2022-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="phone", field=models.CharField(max_length=13),
        ),
    ]
